# Generated by Django 4.1.7 on 2023-03-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_key', models.BigIntegerField(help_text='mem_ID', primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.TextField()),
                ('mem_image', models.ImageField(blank=True, null=True, upload_to='homepage_app/img/member')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_key', models.BigIntegerField(help_text='tft_ID', primary_key=True, serialize=False)),
                ('news_year', models.IntegerField(max_length=4)),
                ('news_name', models.CharField(max_length=32)),
                ('news', models.TextField()),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='homepage_app/img/news')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_key', models.BigIntegerField(help_text='team_ID', primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=32)),
                ('team_explation', models.TextField()),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='homepage_app/img/team')),
            ],
        ),
        migrations.CreateModel(
            name='TFT',
            fields=[
                ('tft_key', models.BigIntegerField(help_text='tft_ID', primary_key=True, serialize=False)),
                ('tft_name', models.CharField(max_length=32)),
                ('tft_explation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TFTImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tft_image', models.ImageField(upload_to='homepage_app/img/tft')),
                ('TFT_ForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage_app.tft')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('pub_key', models.BigIntegerField(help_text='pub_ID', primary_key=True, serialize=False)),
                ('pub_year', models.IntegerField(max_length=4)),
                ('pub_name', models.CharField(max_length=32)),
                ('author_name', models.CharField(max_length=32)),
                ('conference_name', models.CharField(max_length=32)),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, related_name='mem', to='homepage_app.member')),
            ],
        ),
    ]
