# Generated by Django 4.1.7 on 2023-08-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='g_scholar_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
