# Generated by Django 4.1.7 on 2023-08-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0003_publications_pub_pages_alter_publications_m_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='pub_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
