# Generated by Django 4.1.7 on 2023-08-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0005_remove_publications_pub_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='pub_year',
            field=models.IntegerField(null=True),
        ),
    ]
