# Generated by Django 4.1.7 on 2023-08-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0006_alter_publications_pub_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='pub_name',
            field=models.CharField(max_length=256),
        ),
    ]
